# Generated by Django 4.2.3 on 2024-01-04 10:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('purchase', '0003_alter_purchasemaster_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasemaster',
            name='created_at',
            field=models.DateTimeField(
                default=datetime.datetime(2024, 1, 4, 10, 21, 38, 698818, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
