# Generated by Django 4.2.3 on 2024-01-02 15:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255, null=True)),
                ('created_at', models.DateTimeField(
                    default=datetime.datetime(2024, 1, 2, 15, 21, 42, 120964, tzinfo=datetime.timezone.utc),
                    null=True)),
            ],
            options={
                'db_table': 'category',
            },
        ),
    ]
