# Generated by Django 4.2.3 on 2024-01-04 10:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('sale', '0002_alter_salemaster_created_at_alter_saledetail_table_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salemaster',
            old_name='supplier',
            new_name='customer',
        ),
        migrations.AlterField(
            model_name='salemaster',
            name='created_at',
            field=models.DateTimeField(
                default=datetime.datetime(2024, 1, 4, 10, 20, 9, 819654, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
