# Generated by Django 4.2.3 on 2024-01-04 10:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('sale', '0003_rename_supplier_salemaster_customer_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salemaster',
            old_name='purchase_amount',
            new_name='sale_amount',
        ),
        migrations.AlterField(
            model_name='salemaster',
            name='created_at',
            field=models.DateTimeField(
                default=datetime.datetime(2024, 1, 4, 10, 21, 38, 698180, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
